### ISSUE TITLE
Disabling keyboard shortcuts when contenteditable focused

### ISSUE THREAD

**Issue by tommoor** [glortho/react-keydown#51]
Thoughts on how to achieve this? Should it be baked into the library the same way as input and textarea?

**Comment by tommoor** [comment]
So, I think this could be achieved by checking for an aria role of `textarea`.

**Comment by glortho** [comment]
Thanks for this @tommoor - I'll try adding that check for the aria role. Stay tuned.

**Comment by tommoor** [comment]
Great! I forked and did some of the work but unfortunately can't get your test suite to run on node 7.8

You should try cloning and installing into a fresh directory if possible, there might be some dev deps or instructions missing?

**Comment by glortho** [comment]
Okay good to know @tommoor. I'll check it out.

**Comment by glortho** [comment]
I pushed a fix for this in 1.7.1. Give it a try and let me know if it works as expected for you @tommoor

**Comment by tommoor** [comment]
Unfortunately the fix doesn't seem to work - My best guess is because the contenteditable element is full of other elements that are the event `target` when typing. Really the logic should check if any of the parents are role="textarea"…

**Comment by tommoor** [comment]
I checked, the `target` is correct - actually I think the new logic is just wrong. It should be checking that the role **is not** textarea, but it appears to be doing the opposite.

**Comment by glortho** [comment]
doh! midnight regression. sorry about that. it should be correct now in 1.7.2 @tommoor

**Comment by tommoor** [comment]
Hey Jed,

I just got a chance to test this manually - unfortunately the logic is still incorrect because of the **or** between the two checks for a textarea/input. This is why I wanted to figure out how to run your test suite 😆

**Comment by glortho** [comment]
Ah sorry - I'm very distracted at the moment. That's an easy fix but let me
get the tests back in shape and then I'll push everything up.

**Comment by glortho** [comment]
Ok @tommoor tests + this issue should finally be fixed (as of 1.7.3). That was embarrassing. 😬

**Comment by tommoor** [comment]
🙌
